name: CryptoApp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: CryptoApp.sln                                   

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore the application
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Publish the application
      run: dotnet publish
        
    - name: Set the release tag
      run: |
        echo "release_tag=$(date +"%d-%m-%Y_%H-%M")" >> $GITHUB_ENV

    - name: Pack release
      working-directory: ${{github.workspace}}/bin/Debug/net6.0/publish/
      run: |
        zip -r 'CryptoApp' @ "CryptoApp-${{ env.release_tag }}.zip" .
        mv *.zip ..

    - uses: marvinpinto/action-automatic-releases@latest
      name: Create release on GitHub
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "${{ env.release_tag }}"
        files: |
          CryptoApp-${{ env.release_tag }}.zip
